# Generated by Django 5.1 on 2024-08-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transactionhistory_delete_walletaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(choices=[('USDT', 'USDT (TRC-20)'), ('BTC', 'BTC'), ('BCH', 'BCH'), ('ETH', 'ETH')], max_length=10, unique=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
