# Generated by Django 5.1 on 2024-08-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_transaction_pin_withdrawal_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
