# Generated by Django 5.1 on 2024-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profitaddition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='static/profile/'),
        ),
    ]
