# Generated by Django 5.1 on 2024-09-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_ada_profile_avail_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='transaction_pin',
        ),
    ]
