# Generated by Django 5.1 on 2024-09-08 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_withdrawal_transaction_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfitAddition',
            new_name='Earnings',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profits',
            new_name='earnings',
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('earnings', 'Earnings')], max_length=20),
        ),
    ]
