# Generated by Django 5.1 on 2024-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_tax_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_type',
            field=models.CharField(choices=[('USDT', 'USDT (TRC-20)'), ('BTC', 'BTC'), ('BCH', 'BCH'), ('ETH', 'ETH'), ('WIRE', 'Wire Transfer')], default='BTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_type',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (TRC-20)'), ('WIRE', 'Wire Transfer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
