# Generated by Django 5.1 on 2024-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_withdrawal_account_number_withdrawal_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_type',
            field=models.CharField(choices=[('tax', 'Tax'), ('fund', 'Fund'), ('fees', 'Fees'), ('ada', 'ADA')], default='fund', max_length=50),
        ),
    ]
