# Generated by Django 5.1 on 2024-09-09 21:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_transactionhistory_transaction_type_ada'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
